//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace prjQLNK.QLNK
{

    public partial class BAOTU : XPLiteObject
    {
        int fSTT;
        [Key(true)]
        public int STT
        {
            get { return fSTT; }
            set { SetPropertyValue<int>("STT", ref fSTT, value); }
        }
        string fMAKHAISINH;
        [Size(10)]
        public string MAKHAISINH
        {
            get { return fMAKHAISINH; }
            set { SetPropertyValue<string>("MAKHAISINH", ref fMAKHAISINH, value); }
        }
        DateTime fNGAYMAT;
        public DateTime NGAYMAT
        {
            get { return fNGAYMAT; }
            set { SetPropertyValue<DateTime>("NGAYMAT", ref fNGAYMAT, value); }
        }
        string fLYDOMAT;
        public string LYDOMAT
        {
            get { return fLYDOMAT; }
            set { SetPropertyValue<string>("LYDOMAT", ref fLYDOMAT, value); }
        }
        string fGHICHU;
        public string GHICHU
        {
            get { return fGHICHU; }
            set { SetPropertyValue<string>("GHICHU", ref fGHICHU, value); }
        }
        string fMACANBO;
        [Size(10)]
        public string MACANBO
        {
            get { return fMACANBO; }
            set { SetPropertyValue<string>("MACANBO", ref fMACANBO, value); }
        }
        string fNGUOIKHAI;
        [Size(50)]
        public string NGUOIKHAI
        {
            get { return fNGUOIKHAI; }
            set { SetPropertyValue<string>("NGUOIKHAI", ref fNGUOIKHAI, value); }
        }
        DateTime fNGAYKHAI;
        public DateTime NGAYKHAI
        {
            get { return fNGAYKHAI; }
            set { SetPropertyValue<DateTime>("NGAYKHAI", ref fNGAYKHAI, value); }
        }
    }

}
