//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace prjQLNK.QLNK
{

    public partial class CANBO : XPLiteObject
    {
        string fMACANBO;
        [Key]
        [Size(10)]
        public string MACANBO
        {
            get { return fMACANBO; }
            set { SetPropertyValue<string>("MACANBO", ref fMACANBO, value); }
        }
        string fTENCANBO;
        [Size(50)]
        public string TENCANBO
        {
            get { return fTENCANBO; }
            set { SetPropertyValue<string>("TENCANBO", ref fTENCANBO, value); }
        }
        int fGIOITINH;
        public int GIOITINH
        {
            get { return fGIOITINH; }
            set { SetPropertyValue<int>("GIOITINH", ref fGIOITINH, value); }
        }
        DateTime fNGAYSINH;
        public DateTime NGAYSINH
        {
            get { return fNGAYSINH; }
            set { SetPropertyValue<DateTime>("NGAYSINH", ref fNGAYSINH, value); }
        }
        string fCHUCVU;
        [Size(50)]
        public string CHUCVU
        {
            get { return fCHUCVU; }
            set { SetPropertyValue<string>("CHUCVU", ref fCHUCVU, value); }
        }
        string fDIACHI;
        public string DIACHI
        {
            get { return fDIACHI; }
            set { SetPropertyValue<string>("DIACHI", ref fDIACHI, value); }
        }
        string fSDT;
        [Size(12)]
        public string SDT
        {
            get { return fSDT; }
            set { SetPropertyValue<string>("SDT", ref fSDT, value); }
        }
        string fEMAIL;
        [Size(50)]
        public string EMAIL
        {
            get { return fEMAIL; }
            set { SetPropertyValue<string>("EMAIL", ref fEMAIL, value); }
        }
        string fQUYENHAN;
        [Size(50)]
        public string QUYENHAN
        {
            get { return fQUYENHAN; }
            set { SetPropertyValue<string>("QUYENHAN", ref fQUYENHAN, value); }
        }
        [Association(@"NGUOIDUNGReferencesCANBO")]
        public XPCollection<NGUOIDUNG> NGUOIDUNGs { get { return GetCollection<NGUOIDUNG>("NGUOIDUNGs"); } }
        [Association(@"HOKHAUReferencesCANBO")]
        public XPCollection<HOKHAU> HOKHAUs { get { return GetCollection<HOKHAU>("HOKHAUs"); } }
    }

}
