//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace prjQLNK.QLNK
{

    public partial class DANTOC : XPLiteObject
    {
        int fMADANTOC;
        [Key]
        public int MADANTOC
        {
            get { return fMADANTOC; }
            set { SetPropertyValue<int>("MADANTOC", ref fMADANTOC, value); }
        }
        string fTENDANTOC;
        [Size(50)]
        public string TENDANTOC
        {
            get { return fTENDANTOC; }
            set { SetPropertyValue<string>("TENDANTOC", ref fTENDANTOC, value); }
        }
    }

}
