//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace prjQLNK.QLNK
{

    public partial class DIENBIEN : XPLiteObject
    {
        int fSTT;
        [Key(true)]
        public int STT
        {
            get { return fSTT; }
            set { SetPropertyValue<int>("STT", ref fSTT, value); }
        }
        string fMAKHAISINH;
        [Size(10)]
        public string MAKHAISINH
        {
            get { return fMAKHAISINH; }
            set { SetPropertyValue<string>("MAKHAISINH", ref fMAKHAISINH, value); }
        }
        string fNOIDI;
        public string NOIDI
        {
            get { return fNOIDI; }
            set { SetPropertyValue<string>("NOIDI", ref fNOIDI, value); }
        }
        DateTime fNGAYDI;
        public DateTime NGAYDI
        {
            get { return fNGAYDI; }
            set { SetPropertyValue<DateTime>("NGAYDI", ref fNGAYDI, value); }
        }
        string fNOIDEN;
        public string NOIDEN
        {
            get { return fNOIDEN; }
            set { SetPropertyValue<string>("NOIDEN", ref fNOIDEN, value); }
        }
        DateTime fNGAYDEN;
        public DateTime NGAYDEN
        {
            get { return fNGAYDEN; }
            set { SetPropertyValue<DateTime>("NGAYDEN", ref fNGAYDEN, value); }
        }
        string fLYDO;
        public string LYDO
        {
            get { return fLYDO; }
            set { SetPropertyValue<string>("LYDO", ref fLYDO, value); }
        }
        string fTHOIHAN;
        [Size(50)]
        public string THOIHAN
        {
            get { return fTHOIHAN; }
            set { SetPropertyValue<string>("THOIHAN", ref fTHOIHAN, value); }
        }
        string fMACANBO;
        [Size(10)]
        public string MACANBO
        {
            get { return fMACANBO; }
            set { SetPropertyValue<string>("MACANBO", ref fMACANBO, value); }
        }
        DateTime fNGAYLAP;
        public DateTime NGAYLAP
        {
            get { return fNGAYLAP; }
            set { SetPropertyValue<DateTime>("NGAYLAP", ref fNGAYLAP, value); }
        }
    }

}
