//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace prjQLNK.QLNK
{

    public partial class KHENTHUONG : XPLiteObject
    {
        int fSTT;
        [Key(true)]
        public int STT
        {
            get { return fSTT; }
            set { SetPropertyValue<int>("STT", ref fSTT, value); }
        }
        string fMAKHAISINH;
        [Size(10)]
        public string MAKHAISINH
        {
            get { return fMAKHAISINH; }
            set { SetPropertyValue<string>("MAKHAISINH", ref fMAKHAISINH, value); }
        }
        DateTime fNGAYTHANG;
        public DateTime NGAYTHANG
        {
            get { return fNGAYTHANG; }
            set { SetPropertyValue<DateTime>("NGAYTHANG", ref fNGAYTHANG, value); }
        }
        string fCOQUAN;
        [Size(50)]
        public string COQUAN
        {
            get { return fCOQUAN; }
            set { SetPropertyValue<string>("COQUAN", ref fCOQUAN, value); }
        }
        string fSUKIEN;
        [Size(50)]
        public string SUKIEN
        {
            get { return fSUKIEN; }
            set { SetPropertyValue<string>("SUKIEN", ref fSUKIEN, value); }
        }
        string fHINHTHUC;
        [Size(50)]
        public string HINHTHUC
        {
            get { return fHINHTHUC; }
            set { SetPropertyValue<string>("HINHTHUC", ref fHINHTHUC, value); }
        }
        DateTime fNGAYLUU;
        public DateTime NGAYLUU
        {
            get { return fNGAYLUU; }
            set { SetPropertyValue<DateTime>("NGAYLUU", ref fNGAYLUU, value); }
        }
        string fGHICHU;
        [Size(50)]
        public string GHICHU
        {
            get { return fGHICHU; }
            set { SetPropertyValue<string>("GHICHU", ref fGHICHU, value); }
        }
    }

}
