//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace prjQLNK.QLNK
{

    public partial class NHANKHAU : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>("ID", ref fID, value); }
        }
        string fMAKHAISINH;
        [Size(SizeAttribute.Unlimited)]
        public string MAKHAISINH
        {
            get { return fMAKHAISINH; }
            set { SetPropertyValue<string>("MAKHAISINH", ref fMAKHAISINH, value); }
        }
        string fHOTENKHAISINH;
        [Size(SizeAttribute.Unlimited)]
        public string HOTENKHAISINH
        {
            get { return fHOTENKHAISINH; }
            set { SetPropertyValue<string>("HOTENKHAISINH", ref fHOTENKHAISINH, value); }
        }
        string fTENGOIKHAC;
        [Size(SizeAttribute.Unlimited)]
        public string TENGOIKHAC
        {
            get { return fTENGOIKHAC; }
            set { SetPropertyValue<string>("TENGOIKHAC", ref fTENGOIKHAC, value); }
        }
        int fGIOITINH;
        public int GIOITINH
        {
            get { return fGIOITINH; }
            set { SetPropertyValue<int>("GIOITINH", ref fGIOITINH, value); }
        }
        DateTime fNGAYSINH;
        public DateTime NGAYSINH
        {
            get { return fNGAYSINH; }
            set { SetPropertyValue<DateTime>("NGAYSINH", ref fNGAYSINH, value); }
        }
        string fNOISINH;
        [Size(SizeAttribute.Unlimited)]
        public string NOISINH
        {
            get { return fNOISINH; }
            set { SetPropertyValue<string>("NOISINH", ref fNOISINH, value); }
        }
        string fQUEQUAN;
        [Size(SizeAttribute.Unlimited)]
        public string QUEQUAN
        {
            get { return fQUEQUAN; }
            set { SetPropertyValue<string>("QUEQUAN", ref fQUEQUAN, value); }
        }
        string fCHOOHIENNAY;
        [Size(SizeAttribute.Unlimited)]
        public string CHOOHIENNAY
        {
            get { return fCHOOHIENNAY; }
            set { SetPropertyValue<string>("CHOOHIENNAY", ref fCHOOHIENNAY, value); }
        }
        string fDANTOC;
        [Size(SizeAttribute.Unlimited)]
        public string DANTOC
        {
            get { return fDANTOC; }
            set { SetPropertyValue<string>("DANTOC", ref fDANTOC, value); }
        }
        string fTONGIAO;
        [Size(SizeAttribute.Unlimited)]
        public string TONGIAO
        {
            get { return fTONGIAO; }
            set { SetPropertyValue<string>("TONGIAO", ref fTONGIAO, value); }
        }
        string fQUOCTICH;
        [Size(SizeAttribute.Unlimited)]
        public string QUOCTICH
        {
            get { return fQUOCTICH; }
            set { SetPropertyValue<string>("QUOCTICH", ref fQUOCTICH, value); }
        }
        string fSOCMND;
        [Size(SizeAttribute.Unlimited)]
        public string SOCMND
        {
            get { return fSOCMND; }
            set { SetPropertyValue<string>("SOCMND", ref fSOCMND, value); }
        }
        DateTime fNGAYCAP;
        public DateTime NGAYCAP
        {
            get { return fNGAYCAP; }
            set { SetPropertyValue<DateTime>("NGAYCAP", ref fNGAYCAP, value); }
        }
        string fNOICAP;
        [Size(SizeAttribute.Unlimited)]
        public string NOICAP
        {
            get { return fNOICAP; }
            set { SetPropertyValue<string>("NOICAP", ref fNOICAP, value); }
        }
        string fHINHANH;
        [Size(SizeAttribute.Unlimited)]
        public string HINHANH
        {
            get { return fHINHANH; }
            set { SetPropertyValue<string>("HINHANH", ref fHINHANH, value); }
        }
        string fNOIDKHKTT;
        [Size(SizeAttribute.Unlimited)]
        public string NOIDKHKTT
        {
            get { return fNOIDKHKTT; }
            set { SetPropertyValue<string>("NOIDKHKTT", ref fNOIDKHKTT, value); }
        }
        string fTRINHDO;
        [Size(SizeAttribute.Unlimited)]
        public string TRINHDO
        {
            get { return fTRINHDO; }
            set { SetPropertyValue<string>("TRINHDO", ref fTRINHDO, value); }
        }
        string fNGHENGHIEP;
        [Size(SizeAttribute.Unlimited)]
        public string NGHENGHIEP
        {
            get { return fNGHENGHIEP; }
            set { SetPropertyValue<string>("NGHENGHIEP", ref fNGHENGHIEP, value); }
        }
        string fDAUVET;
        [Size(SizeAttribute.Unlimited)]
        public string DAUVET
        {
            get { return fDAUVET; }
            set { SetPropertyValue<string>("DAUVET", ref fDAUVET, value); }
        }
        string fNGUOIKHAI;
        [Size(SizeAttribute.Unlimited)]
        public string NGUOIKHAI
        {
            get { return fNGUOIKHAI; }
            set { SetPropertyValue<string>("NGUOIKHAI", ref fNGUOIKHAI, value); }
        }
        DateTime fNGAYKHAI;
        public DateTime NGAYKHAI
        {
            get { return fNGAYKHAI; }
            set { SetPropertyValue<DateTime>("NGAYKHAI", ref fNGAYKHAI, value); }
        }
        string fMACANBO;
        [Size(SizeAttribute.Unlimited)]
        public string MACANBO
        {
            get { return fMACANBO; }
            set { SetPropertyValue<string>("MACANBO", ref fMACANBO, value); }
        }
        int fSOHOKHAU;
        [Indexed(Name = @"iSOHOKHAU_NHANKHAU")]
        public int SOHOKHAU
        {
            get { return fSOHOKHAU; }
            set { SetPropertyValue<int>("SOHOKHAU", ref fSOHOKHAU, value); }
        }
        string fGHICHU;
        [Size(SizeAttribute.Unlimited)]
        public string GHICHU
        {
            get { return fGHICHU; }
            set { SetPropertyValue<string>("GHICHU", ref fGHICHU, value); }
        }
        string fNOIDKKHAISINH;
        [Size(SizeAttribute.Unlimited)]
        public string NOIDKKHAISINH
        {
            get { return fNOIDKKHAISINH; }
            set { SetPropertyValue<string>("NOIDKKHAISINH", ref fNOIDKKHAISINH, value); }
        }
        string fNGUOIKHAISINH;
        [Size(SizeAttribute.Unlimited)]
        public string NGUOIKHAISINH
        {
            get { return fNGUOIKHAISINH; }
            set { SetPropertyValue<string>("NGUOIKHAISINH", ref fNGUOIKHAISINH, value); }
        }
        DateTime fNGAYDKKHAISINH;
        public DateTime NGAYDKKHAISINH
        {
            get { return fNGAYDKKHAISINH; }
            set { SetPropertyValue<DateTime>("NGAYDKKHAISINH", ref fNGAYDKKHAISINH, value); }
        }
        string fSOHOCHIEU;
        [Size(SizeAttribute.Unlimited)]
        public string SOHOCHIEU
        {
            get { return fSOHOCHIEU; }
            set { SetPropertyValue<string>("SOHOCHIEU", ref fSOHOCHIEU, value); }
        }
        DateTime fNCHOCHIEU;
        public DateTime NCHOCHIEU
        {
            get { return fNCHOCHIEU; }
            set { SetPropertyValue<DateTime>("NCHOCHIEU", ref fNCHOCHIEU, value); }
        }
        string fCQCAPHOCHIEU;
        [Size(SizeAttribute.Unlimited)]
        public string CQCAPHOCHIEU
        {
            get { return fCQCAPHOCHIEU; }
            set { SetPropertyValue<string>("CQCAPHOCHIEU", ref fCQCAPHOCHIEU, value); }
        }
        string fQUANHEKHAISINH;
        [Size(SizeAttribute.Unlimited)]
        public string QUANHEKHAISINH
        {
            get { return fQUANHEKHAISINH; }
            set { SetPropertyValue<string>("QUANHEKHAISINH", ref fQUANHEKHAISINH, value); }
        }
        string fTDCHUYENMON;
        [Size(SizeAttribute.Unlimited)]
        public string TDCHUYENMON
        {
            get { return fTDCHUYENMON; }
            set { SetPropertyValue<string>("TDCHUYENMON", ref fTDCHUYENMON, value); }
        }
        string fNOILAMVIEC;
        [Size(SizeAttribute.Unlimited)]
        public string NOILAMVIEC
        {
            get { return fNOILAMVIEC; }
            set { SetPropertyValue<string>("NOILAMVIEC", ref fNOILAMVIEC, value); }
        }
        string fNOITHUONGTRU;
        [Size(SizeAttribute.Unlimited)]
        public string NOITHUONGTRU
        {
            get { return fNOITHUONGTRU; }
            set { SetPropertyValue<string>("NOITHUONGTRU", ref fNOITHUONGTRU, value); }
        }
        byte[] fHINHANHCD;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] HINHANHCD
        {
            get { return fHINHANHCD; }
            set { SetPropertyValue<byte[]>("HINHANHCD", ref fHINHANHCD, value); }
        }
        string fIDQG1;
        [Size(SizeAttribute.Unlimited)]
        public string IDQG1
        {
            get { return fIDQG1; }
            set { SetPropertyValue<string>("IDQG1", ref fIDQG1, value); }
        }
        string fIDQG2;
        [Size(SizeAttribute.Unlimited)]
        public string IDQG2
        {
            get { return fIDQG2; }
            set { SetPropertyValue<string>("IDQG2", ref fIDQG2, value); }
        }
        string fIDQG3;
        [Size(SizeAttribute.Unlimited)]
        public string IDQG3
        {
            get { return fIDQG3; }
            set { SetPropertyValue<string>("IDQG3", ref fIDQG3, value); }
        }
        string fIDQG4;
        [Size(SizeAttribute.Unlimited)]
        public string IDQG4
        {
            get { return fIDQG4; }
            set { SetPropertyValue<string>("IDQG4", ref fIDQG4, value); }
        }
        string fIDTINH1;
        [Size(SizeAttribute.Unlimited)]
        public string IDTINH1
        {
            get { return fIDTINH1; }
            set { SetPropertyValue<string>("IDTINH1", ref fIDTINH1, value); }
        }
        string fIDTINH2;
        [Size(SizeAttribute.Unlimited)]
        public string IDTINH2
        {
            get { return fIDTINH2; }
            set { SetPropertyValue<string>("IDTINH2", ref fIDTINH2, value); }
        }
        string fIDTINH3;
        [Size(SizeAttribute.Unlimited)]
        public string IDTINH3
        {
            get { return fIDTINH3; }
            set { SetPropertyValue<string>("IDTINH3", ref fIDTINH3, value); }
        }
        string fIDTINH4;
        [Size(SizeAttribute.Unlimited)]
        public string IDTINH4
        {
            get { return fIDTINH4; }
            set { SetPropertyValue<string>("IDTINH4", ref fIDTINH4, value); }
        }
        string fIDHUYEN1;
        [Size(SizeAttribute.Unlimited)]
        public string IDHUYEN1
        {
            get { return fIDHUYEN1; }
            set { SetPropertyValue<string>("IDHUYEN1", ref fIDHUYEN1, value); }
        }
        string fIDHUYEN2;
        [Size(SizeAttribute.Unlimited)]
        public string IDHUYEN2
        {
            get { return fIDHUYEN2; }
            set { SetPropertyValue<string>("IDHUYEN2", ref fIDHUYEN2, value); }
        }
        string fIDHUYEN3;
        [Size(SizeAttribute.Unlimited)]
        public string IDHUYEN3
        {
            get { return fIDHUYEN3; }
            set { SetPropertyValue<string>("IDHUYEN3", ref fIDHUYEN3, value); }
        }
        string fIDHUYEN4;
        [Size(SizeAttribute.Unlimited)]
        public string IDHUYEN4
        {
            get { return fIDHUYEN4; }
            set { SetPropertyValue<string>("IDHUYEN4", ref fIDHUYEN4, value); }
        }
        string fIDXA1;
        [Size(SizeAttribute.Unlimited)]
        public string IDXA1
        {
            get { return fIDXA1; }
            set { SetPropertyValue<string>("IDXA1", ref fIDXA1, value); }
        }
        string fIDXA2;
        [Size(SizeAttribute.Unlimited)]
        public string IDXA2
        {
            get { return fIDXA2; }
            set { SetPropertyValue<string>("IDXA2", ref fIDXA2, value); }
        }
        string fIDXA3;
        [Size(SizeAttribute.Unlimited)]
        public string IDXA3
        {
            get { return fIDXA3; }
            set { SetPropertyValue<string>("IDXA3", ref fIDXA3, value); }
        }
        string fIDXA4;
        [Size(SizeAttribute.Unlimited)]
        public string IDXA4
        {
            get { return fIDXA4; }
            set { SetPropertyValue<string>("IDXA4", ref fIDXA4, value); }
        }
        string fDC1;
        [Size(SizeAttribute.Unlimited)]
        public string DC1
        {
            get { return fDC1; }
            set { SetPropertyValue<string>("DC1", ref fDC1, value); }
        }
        string fDC2;
        [Size(SizeAttribute.Unlimited)]
        public string DC2
        {
            get { return fDC2; }
            set { SetPropertyValue<string>("DC2", ref fDC2, value); }
        }
        string fDC3;
        [Size(SizeAttribute.Unlimited)]
        public string DC3
        {
            get { return fDC3; }
            set { SetPropertyValue<string>("DC3", ref fDC3, value); }
        }
        string fDC4;
        [Size(SizeAttribute.Unlimited)]
        public string DC4
        {
            get { return fDC4; }
            set { SetPropertyValue<string>("DC4", ref fDC4, value); }
        }
        int fIDQUATRINH;
        [Indexed(Name = @"iIDQUATRINH_NHANKHAU")]
        public int IDQUATRINH
        {
            get { return fIDQUATRINH; }
            set { SetPropertyValue<int>("IDQUATRINH", ref fIDQUATRINH, value); }
        }
        string fQUANHE;
        [Size(SizeAttribute.Unlimited)]
        public string QUANHE
        {
            get { return fQUANHE; }
            set { SetPropertyValue<string>("QUANHE", ref fQUANHE, value); }
        }
        string fBIETTIENGDANTOC;
        [Size(SizeAttribute.Unlimited)]
        public string BIETTIENGDANTOC
        {
            get { return fBIETTIENGDANTOC; }
            set { SetPropertyValue<string>("BIETTIENGDANTOC", ref fBIETTIENGDANTOC, value); }
        }
        string fTDNGOAINGU;
        [Size(SizeAttribute.Unlimited)]
        public string TDNGOAINGU
        {
            get { return fTDNGOAINGU; }
            set { SetPropertyValue<string>("TDNGOAINGU", ref fTDNGOAINGU, value); }
        }
        bool fDAMAT;
        public bool DAMAT
        {
            get { return fDAMAT; }
            set { SetPropertyValue<bool>("DAMAT", ref fDAMAT, value); }
        }
    }

}
