//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace prjQLNK.QLNK
{

    public partial class NHAPKHAU : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>("ID", ref fID, value); }
        }
        string fMAKHAISINH;
        [Size(SizeAttribute.Unlimited)]
        public string MAKHAISINH
        {
            get { return fMAKHAISINH; }
            set { SetPropertyValue<string>("MAKHAISINH", ref fMAKHAISINH, value); }
        }
        int fSOHOKHAUHT;
        public int SOHOKHAUHT
        {
            get { return fSOHOKHAUHT; }
            set { SetPropertyValue<int>("SOHOKHAUHT", ref fSOHOKHAUHT, value); }
        }
        int fSOHOKHAUNHAP;
        public int SOHOKHAUNHAP
        {
            get { return fSOHOKHAUNHAP; }
            set { SetPropertyValue<int>("SOHOKHAUNHAP", ref fSOHOKHAUNHAP, value); }
        }
        DateTime fNGAYNHAP;
        public DateTime NGAYNHAP
        {
            get { return fNGAYNHAP; }
            set { SetPropertyValue<DateTime>("NGAYNHAP", ref fNGAYNHAP, value); }
        }
        string fQUANHEVOICH;
        [Size(SizeAttribute.Unlimited)]
        public string QUANHEVOICH
        {
            get { return fQUANHEVOICH; }
            set { SetPropertyValue<string>("QUANHEVOICH", ref fQUANHEVOICH, value); }
        }
    }

}
