//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace prjQLNK.QLNK
{

    public partial class QUANHE : XPLiteObject
    {
        int fSTT;
        [Key(true)]
        public int STT
        {
            get { return fSTT; }
            set { SetPropertyValue<int>("STT", ref fSTT, value); }
        }
        string fMAKHAISINH;
        [Size(10)]
        public string MAKHAISINH
        {
            get { return fMAKHAISINH; }
            set { SetPropertyValue<string>("MAKHAISINH", ref fMAKHAISINH, value); }
        }
        string fHOTEN;
        [Size(50)]
        public string HOTEN
        {
            get { return fHOTEN; }
            set { SetPropertyValue<string>("HOTEN", ref fHOTEN, value); }
        }
        int fGIOITINH;
        public int GIOITINH
        {
            get { return fGIOITINH; }
            set { SetPropertyValue<int>("GIOITINH", ref fGIOITINH, value); }
        }
        DateTime fNGAYSINH;
        public DateTime NGAYSINH
        {
            get { return fNGAYSINH; }
            set { SetPropertyValue<DateTime>("NGAYSINH", ref fNGAYSINH, value); }
        }
        string fDANTOC;
        [Size(50)]
        public string DANTOC
        {
            get { return fDANTOC; }
            set { SetPropertyValue<string>("DANTOC", ref fDANTOC, value); }
        }
        string fQUOCTICH;
        [Size(50)]
        public string QUOCTICH
        {
            get { return fQUOCTICH; }
            set { SetPropertyValue<string>("QUOCTICH", ref fQUOCTICH, value); }
        }
        string fQUANHE1;
        [Size(50)]
        [Persistent(@"QUANHE")]
        public string QUANHE1
        {
            get { return fQUANHE1; }
            set { SetPropertyValue<string>("QUANHE1", ref fQUANHE1, value); }
        }
        string fNGHENGHIEP;
        [Size(50)]
        public string NGHENGHIEP
        {
            get { return fNGHENGHIEP; }
            set { SetPropertyValue<string>("NGHENGHIEP", ref fNGHENGHIEP, value); }
        }
        string fCHOO;
        public string CHOO
        {
            get { return fCHOO; }
            set { SetPropertyValue<string>("CHOO", ref fCHOO, value); }
        }
    }

}
