//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace prjQLNK.QLNK
{

    public partial class QUATRINH : XPLiteObject
    {
        int fSTT;
        [Key(true)]
        public int STT
        {
            get { return fSTT; }
            set { SetPropertyValue<int>("STT", ref fSTT, value); }
        }
        string fMAKHAISINH;
        [Size(10)]
        public string MAKHAISINH
        {
            get { return fMAKHAISINH; }
            set { SetPropertyValue<string>("MAKHAISINH", ref fMAKHAISINH, value); }
        }
        DateTime fTUTHANGNAM;
        public DateTime TUTHANGNAM
        {
            get { return fTUTHANGNAM; }
            set { SetPropertyValue<DateTime>("TUTHANGNAM", ref fTUTHANGNAM, value); }
        }
        DateTime fDENTHANGNAM;
        public DateTime DENTHANGNAM
        {
            get { return fDENTHANGNAM; }
            set { SetPropertyValue<DateTime>("DENTHANGNAM", ref fDENTHANGNAM, value); }
        }
        string fCHOO;
        public string CHOO
        {
            get { return fCHOO; }
            set { SetPropertyValue<string>("CHOO", ref fCHOO, value); }
        }
        string fNGHENGHIEP;
        [Size(50)]
        public string NGHENGHIEP
        {
            get { return fNGHENGHIEP; }
            set { SetPropertyValue<string>("NGHENGHIEP", ref fNGHENGHIEP, value); }
        }
        string fNOILAMVIEC;
        public string NOILAMVIEC
        {
            get { return fNOILAMVIEC; }
            set { SetPropertyValue<string>("NOILAMVIEC", ref fNOILAMVIEC, value); }
        }
        string fGHICHU;
        public string GHICHU
        {
            get { return fGHICHU; }
            set { SetPropertyValue<string>("GHICHU", ref fGHICHU, value); }
        }
    }

}
