//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace prjQLNK.QLNK
{

    public partial class QUOCTICH : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>("ID", ref fID, value); }
        }
        string fTENQUOCTICH;
        [Size(SizeAttribute.Unlimited)]
        public string TENQUOCTICH
        {
            get { return fTENQUOCTICH; }
            set { SetPropertyValue<string>("TENQUOCTICH", ref fTENQUOCTICH, value); }
        }
    }

}
