//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace prjQLNK.QLNK
{

    public partial class TAMVANG : XPLiteObject
    {
        int fSTT;
        [Key(true)]
        public int STT
        {
            get { return fSTT; }
            set { SetPropertyValue<int>("STT", ref fSTT, value); }
        }
        string fMAKHAISINH;
        [Size(10)]
        public string MAKHAISINH
        {
            get { return fMAKHAISINH; }
            set { SetPropertyValue<string>("MAKHAISINH", ref fMAKHAISINH, value); }
        }
        DateTime fNGAYVANG;
        public DateTime NGAYVANG
        {
            get { return fNGAYVANG; }
            set { SetPropertyValue<DateTime>("NGAYVANG", ref fNGAYVANG, value); }
        }
        DateTime fNGAYKETTHUC;
        public DateTime NGAYKETTHUC
        {
            get { return fNGAYKETTHUC; }
            set { SetPropertyValue<DateTime>("NGAYKETTHUC", ref fNGAYKETTHUC, value); }
        }
        string fLYDO;
        public string LYDO
        {
            get { return fLYDO; }
            set { SetPropertyValue<string>("LYDO", ref fLYDO, value); }
        }
        string fNOIDEN;
        public string NOIDEN
        {
            get { return fNOIDEN; }
            set { SetPropertyValue<string>("NOIDEN", ref fNOIDEN, value); }
        }
        string fNGUOIKHAIBAO;
        [Size(50)]
        public string NGUOIKHAIBAO
        {
            get { return fNGUOIKHAIBAO; }
            set { SetPropertyValue<string>("NGUOIKHAIBAO", ref fNGUOIKHAIBAO, value); }
        }
        string fMACANBO;
        [Size(10)]
        public string MACANBO
        {
            get { return fMACANBO; }
            set { SetPropertyValue<string>("MACANBO", ref fMACANBO, value); }
        }
        DateTime fNGAYLAP;
        public DateTime NGAYLAP
        {
            get { return fNGAYLAP; }
            set { SetPropertyValue<DateTime>("NGAYLAP", ref fNGAYLAP, value); }
        }
        string fGHICHU;
        public string GHICHU
        {
            get { return fGHICHU; }
            set { SetPropertyValue<string>("GHICHU", ref fGHICHU, value); }
        }
    }

}
