//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace prjQLNK.QLNK
{

    public partial class TIENAN : XPLiteObject
    {
        int fSTT;
        [Key(true)]
        public int STT
        {
            get { return fSTT; }
            set { SetPropertyValue<int>("STT", ref fSTT, value); }
        }
        string fMAKHAISINH;
        [Size(SizeAttribute.Unlimited)]
        public string MAKHAISINH
        {
            get { return fMAKHAISINH; }
            set { SetPropertyValue<string>("MAKHAISINH", ref fMAKHAISINH, value); }
        }
        string fTOIDANH;
        [Size(SizeAttribute.Unlimited)]
        public string TOIDANH
        {
            get { return fTOIDANH; }
            set { SetPropertyValue<string>("TOIDANH", ref fTOIDANH, value); }
        }
        string fHINHPHAT;
        [Size(SizeAttribute.Unlimited)]
        public string HINHPHAT
        {
            get { return fHINHPHAT; }
            set { SetPropertyValue<string>("HINHPHAT", ref fHINHPHAT, value); }
        }
        string fSOBANAN;
        [Size(SizeAttribute.Unlimited)]
        public string SOBANAN
        {
            get { return fSOBANAN; }
            set { SetPropertyValue<string>("SOBANAN", ref fSOBANAN, value); }
        }
        DateTime fNGAYTHANG;
        public DateTime NGAYTHANG
        {
            get { return fNGAYTHANG; }
            set { SetPropertyValue<DateTime>("NGAYTHANG", ref fNGAYTHANG, value); }
        }
        DateTime fNGAYLUU;
        public DateTime NGAYLUU
        {
            get { return fNGAYLUU; }
            set { SetPropertyValue<DateTime>("NGAYLUU", ref fNGAYLUU, value); }
        }
        string fGHICHU;
        [Size(SizeAttribute.Unlimited)]
        public string GHICHU
        {
            get { return fGHICHU; }
            set { SetPropertyValue<string>("GHICHU", ref fGHICHU, value); }
        }
    }

}
