//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace prjQLNK.QLNK
{

    public partial class TINH : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>("ID", ref fID, value); }
        }
        int fMATINH;
        public int MATINH
        {
            get { return fMATINH; }
            set { SetPropertyValue<int>("MATINH", ref fMATINH, value); }
        }
        string fTENTINH;
        [Size(SizeAttribute.Unlimited)]
        public string TENTINH
        {
            get { return fTENTINH; }
            set { SetPropertyValue<string>("TENTINH", ref fTENTINH, value); }
        }
        string fLOAI;
        [Size(SizeAttribute.Unlimited)]
        public string LOAI
        {
            get { return fLOAI; }
            set { SetPropertyValue<string>("LOAI", ref fLOAI, value); }
        }
        int fIDQUOCGIA;
        public int IDQUOCGIA
        {
            get { return fIDQUOCGIA; }
            set { SetPropertyValue<int>("IDQUOCGIA", ref fIDQUOCGIA, value); }
        }
    }

}
