//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace prjQLNK.QLNK
{

    public partial class TONGIAO : XPLiteObject
    {
        int fMATONGIAO;
        [Key]
        public int MATONGIAO
        {
            get { return fMATONGIAO; }
            set { SetPropertyValue<int>("MATONGIAO", ref fMATONGIAO, value); }
        }
        string fTENTONGIAO;
        [Size(50)]
        public string TENTONGIAO
        {
            get { return fTENTONGIAO; }
            set { SetPropertyValue<string>("TENTONGIAO", ref fTENTONGIAO, value); }
        }
    }

}
